"""empty message

Revision ID: fae5cecf372c
Revises: None
Create Date: 2016-06-29 17:20:38.485502

"""

# revision identifiers, used by Alembic.
revision = 'fae5cecf372c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', sa.String(length=1500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'description')
    ### end Alembic commands ###
